apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: face-emotion
  name: face-emotion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: face-emotion
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: face-emotion
    spec:
      containers:
        - image: face-emotion
          imagePullPolicy: Never
          name: face-emotion
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
