apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: triton
  name: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: triton
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: triton
    spec:
      volumes:                          
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 2048Mi
      containers:
        - args:
            - tritonserver
            - --model-repository=s3://aerial-detection-mlops4/model/Visdrone/Yolov7/triton-deploy/models/ 
            - --strict-model-config=false
            - --gpus=all

          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: aws-env
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  key: AWS_DEFAULT_REGION
                  name: aws-env
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: aws-env
          image: nvcr.io/nvidia/tritonserver:22.02-py3
          name: triton
          # runtime: nvidia
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
          # shm_size: 2g
          # ulimits:
          #   memlock: -1
          #   stack: 67108864
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: grpc
            - containerPort: 8002
              name: metrics
          resources:
            requests:
              memory: 2Gi
              cpu: 2
              nvidia.com/gpu: 1
            limits:
              memory: 5Gi
              cpu: 4
              nvidia.com/gpu: 1

      restartPolicy: Always
status: {}
