apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: triton
  name: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: triton
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: triton
    spec:
      containers:
        - args:
            - tritonserver
            - --model-repository=s3://aerial-detection-mlops4/model/Visdrone/Yolov7/triton-deploy/models/ 
            - --strict-model-config=false

          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: aws-env
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  key: AWS_DEFAULT_REGION
                  name: aws-env
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: aws-env
          image: nvcr.io/nvidia/tritonserver:22.02-py3
          name: triton
          runtime: nvidia
          shm_size: 2g
              ulimits:
                  memlock: -1
                  stack: 67108864
              env_file:
                  - .aws.env
                ports:
                  - containerPort: 8000
                    name: http
                  - containerPort: 8001
                    name: grpc
                  - containerPort: 8002
                    name: metrics
                resources:
                  limits:
                    nvidia.com/gpu: 1

      restartPolicy: Always
status: {}
