apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: webapp
  name: pet-bokeh
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: webapp
    spec:
      containers:
        - image: 681261969843.dkr.ecr.us-east-1.amazonaws.com/mlo4petbokeh:latest
          name: webapp
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
